version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: market_place
      MYSQL_USER: daniel_user
      MYSQL_PASSWORD: daniel_password
      MYSQL_ROOT_PASSWORD: daniel_root_password
    ports:
      - "33306:3306"
    restart: always

  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html